[package]
name = "duckydeck-cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
duckydeck-core.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt"] }

[lints]
workspace = true

[[bin]]
name = "duckydeck"
path = "src/main.rs"
