[package]
name = "duckydeck-cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
duckydeck-core.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

[[bin]]
name = "duckydeck"
path = "src/main.rs"
