//! Validates the icons listed in `assets/icons.toml` and embeds them via
//! `include_bytes!`. A bad or missing icon fails the build.

// Panicking is how a build script reports errors.
#![allow(clippy::expect_used, clippy::panic)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

const SKIP: [&str; 2] = ["tabler", "pairs"];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let assets = manifest.join("../../assets");
    let toml_path = assets.join("icons.toml");
    println!("cargo::rerun-if-changed={}", toml_path.display());
    println!("cargo::rerun-if-changed={}", assets.join("icons").display());

    let text = fs::read_to_string(&toml_path).expect("read assets/icons.toml");
    let table: toml::Table = text.parse().expect("parse assets/icons.toml");

    // name -> path; a name must be unique across categories.
    let mut icons = BTreeMap::new();
    for (category, entries) in &table {
        if SKIP.contains(&category.as_str()) {
            continue;
        }
        let entries = entries.as_table().expect("category must be a table");
        for name in entries.keys() {
            let path = assets
                .join("icons")
                .join(category)
                .join(format!("{name}.svg"));
            validate(&path);
            let path = path.canonicalize().expect("canonical icon path");
            if icons.insert(name.clone(), path).is_some() {
                panic!("icon name `{name}` is listed twice");
            }
        }
    }

    let pairs = table.get("pairs").and_then(|p| p.as_table());
    for (on, off) in pairs.into_iter().flatten() {
        let off = off.as_str().expect("pair value must be a string");
        assert!(icons.contains_key(on), "pair `{on}` is not an icon");
        assert!(icons.contains_key(off), "pair `{off}` is not an icon");
    }

    let mut out =
        String::from("/// Generated by build.rs from assets/icons.toml, sorted by name.\n");
    out.push_str("pub static ICONS: &[(&str, &[u8])] = &[\n");
    for (name, path) in &icons {
        writeln!(out, "    ({name:?}, include_bytes!({:?})),", path.display()).ok();
    }
    out.push_str("];\n");
    let dest = PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("icons.rs");
    fs::write(dest, out).expect("write icons.rs");
}

/// Monochrome, 24 grid, no bitmaps, no embedded styles.
fn validate(path: &Path) {
    let svg = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {e} (run scripts/fetch-icons.sh)", path.display()));
    let fail = |why: &str| panic!("{}: {why}", path.display());
    if !svg.contains(r#"viewBox="0 0 24 24""#) {
        fail("viewBox must be 0 0 24 24");
    }
    for bad in ["<image", "data:", "style=", "<style"] {
        if svg.contains(bad) {
            fail(&format!("must not contain `{bad}`"));
        }
    }
    if !svg.contains("currentColor") {
        fail("must use currentColor");
    }
    for attr in ["fill=\"", "stroke=\""] {
        for value in svg.split(attr).skip(1) {
            let value = value.split('"').next().unwrap_or_default();
            if value != "none" && value != "currentColor" {
                fail(&format!("{attr}{value}\" – only currentColor or none"));
            }
        }
    }
}
