#!/usr/bin/env bash
# Generates docs/omarchy-reference.md from the installed Omarchy.
# Usage: scripts/gen-omarchy-reference.sh   (re-run after Omarchy updates)
# Only extracts what DuckyDeck needs; never modifies anything under /usr/share/omarchy.
set -euo pipefail
cd "$(dirname "$0")/.."

OMARCHY=/usr/share/omarchy
SHELL_DIR=$OMARCHY/shell
OUT=docs/omarchy-reference.md
# Command groups DuckyDeck uses for actions and feedback.
GROUPS_RE='^(audio|brightness|capture|font|hyprland|launch|menu|notification|osd|plugin|restart|shell|system|theme|toggle|tui|webapp)$'

command -v omarchy >/dev/null || { echo "omarchy not found" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq not found" >&2; exit 1; }

# Prints the IpcHandler blocks (target + function signatures) of a QML file.
ipc_handlers() {
  awk '
    /IpcHandler[[:space:]]*\{/ { inside = 1; depth = 0 }
    inside {
      if (match($0, /target:[[:space:]]*[^[:space:]]+/)) { t = substr($0, RSTART, RLENGTH); sub(/target:[[:space:]]*/, "", t); if (t ~ /^"/) { gsub(/"/, "", t); print "- target `" t "`" } else print "- target from property `" t "` (" FILENAME ")" }
      if (match($0, /function [A-Za-z0-9_]+\([^)]*\)(: *[A-Za-z]+)?/)) print "  - `" substr($0, RSTART + 9, RLENGTH - 9) "`"
      n = gsub(/\{/, "{"); m = gsub(/\}/, "}"); depth += n - m
      if (depth <= 0 && n + m > 0) inside = 0
    }' "$1"
}

# Prints the public (non-underscore) properties declared at the top level of a QML file.
qml_props() {
  grep -E '^  (readonly |required |default )*property [A-Za-z<>.]+ [a-zA-Z][A-Za-z0-9]*' "$1" \
    | sed -E 's/^  (readonly |required |default )*property ([A-Za-z<>.]+) ([A-Za-z0-9]+).*/\3: \2/' \
    | paste -sd ',' | sed 's/,/, /g'
}

{
  echo "# Omarchy reference (generated)"
  echo
  echo "Generated by \`scripts/gen-omarchy-reference.sh\` – do not edit by hand."
  echo "Omarchy $(omarchy version 2>/dev/null | head -n1) · $(date -I)"
  echo
  echo "## Command routes"
  echo
  echo "Groups relevant to DuckyDeck only. Full list: \`omarchy commands --json\`. ⚠ = requires sudo."
  echo
  omarchy commands --json | jq -r --arg re "$GROUPS_RE" '
    .commands
    | map(select((.group | test($re)) and (.hidden | not)))
    | group_by(.group)[]
    | ("### " + .[0].group + "\n\n| Route | Args | Summary |\n|---|---|---|"),
      (sort_by(.route)[] | "| `\(.route)` | \(.args // "" | gsub("\\|"; "\\|")) | \(.summary | gsub("\\|"; "\\|"))\(if .requires_sudo then " ⚠" else "" end) |"),
      ""'

  echo "## Shell IPC (\`omarchy-shell <target> <method> [args…]\`)"
  echo
  for f in "$SHELL_DIR/shell.qml" "$SHELL_DIR/plugins/osd/Osd.qml" "$SHELL_DIR/Ui/Panel.qml"; do
    ipc_handlers "$f"
  done
  echo

  echo "## Plugin system"
  echo
  echo "User plugins: \`~/.config/omarchy/plugins/<id>/manifest.json\`. Kinds in use by first-party plugins:"
  echo
  echo '| id | kinds | entry points |'
  echo '|---|---|---|'
  find "$SHELL_DIR/plugins" -name manifest.json | sort | while read -r m; do
    jq -r '"| `\(.id)` | \(.kinds | join(", ")) | \(.entryPoints | to_entries | map("\(.key): `\(.value)`") | join(", ")) |"' "$m"
  done
  echo
  for example in panels/audio services/media; do
    echo "Example manifest \`plugins/$example/manifest.json\`:"
    echo
    echo '```json'
    cat "$SHELL_DIR/plugins/$example/manifest.json"
    echo '```'
    echo
  done

  echo "## Shell UI components (\`$SHELL_DIR/Ui/\`)"
  echo
  echo "Top-level public properties per component."
  echo
  for f in "$SHELL_DIR"/Ui/*.qml; do
    props=$(qml_props "$f")
    echo "- **$(basename "$f" .qml)**${props:+ – $props}"
  done
  echo

  echo "## Shell tokens (\`$SHELL_DIR/Commons/\`)"
  echo
  for f in Style Color; do
    echo "- **$f**: $(qml_props "$SHELL_DIR/Commons/$f.qml")"
  done
  echo

  echo "## Theme colors"
  echo
  echo "\`~/.local/state/omarchy/current/theme/colors.toml\` keys (current theme):"
  echo
  colors=~/.local/state/omarchy/current/theme/colors.toml
  if [[ -f $colors ]]; then
    grep -oE '^[a-z_0-9]+' "$colors" | paste -sd ' ' | sed -E 's/([^ ]+)/`\1`/g; s/ /, /g'
  else
    echo "(no current theme found)"
  fi
  echo

  echo "## Hooks"
  echo
  echo "User hook directories \`~/.config/omarchy/hooks/<event>.d/\`, events shipped by Omarchy:"
  echo
  ls "$OMARCHY/config/omarchy/hooks" | sed -E 's/\.sample$//; s/\.d$//' | sort -u | sed 's/.*/- `&`/'
  echo

  echo "## Menu extensions"
  echo
  echo "\`~/.config/omarchy/extensions/omarchy-menu.jsonc\` – template comment:"
  echo
  echo '```jsonc'
  sed -n '/^  \/\/ Fields:/,/^  \/\/$/p' "$OMARCHY/config/omarchy/extensions/omarchy-menu.jsonc"
  echo '```'
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
